"""Resolve each company in companies.txt to an ATS endpoint.

For every company we generate a few candidate slugs and probe each ATS
(Greenhouse -> Ashby -> Lever -> Workable -> SmartRecruiters). The first
endpoint that returns a non-empty job list wins. Results are written to
companies.yaml, which is hand-editable: fix a wrong slug, or add a resolved
entry for any company left under `unresolved:`.

Usage:
    python discover.py            # probe all, write companies.yaml
    python discover.py --limit 20 # quick smoke test on first 20 companies
"""
from __future__ import annotations

import argparse
import re
import sys
from concurrent.futures import ThreadPoolExecutor, as_completed

import yaml

from ats import ADAPTERS

HERE = __file__.rsplit("/", 1)[0]
COMPANIES_TXT = f"{HERE}/companies.txt"
COMPANIES_YAML = f"{HERE}/companies.yaml"

# Suffix words dropped when generating a bare candidate slug.
SUFFIXES = {
    "ai", "labs", "lab", "inc", "io", "hq", "technologies", "technology",
    "industries", "systems", "energy", "computer", "robotics", "intelligence",
    "analytics", "security", "games", "the", "co", "corp",
}


def read_companies(path):
    out = []
    with open(path) as f:
        for line in f:
            line = line.strip()
            if line and not line.startswith("#"):
                out.append(line)
    # de-dup preserving order
    seen, uniq = set(), []
    for c in out:
        k = c.lower()
        if k not in seen:
            seen.add(k)
            uniq.append(c)
    return uniq


def candidate_slugs(name):
    """Generate ordered, de-duplicated candidate slugs for a company name."""
    # strip a trailing domain like ".ai" / ".sh" / ".dev"
    base = re.sub(r"\.(ai|sh|dev|io|com|app)$", "", name.strip(), flags=re.I)
    # keep only alphanumerics and spaces
    clean = re.sub(r"[^a-z0-9 ]", " ", base.lower())
    words = [w for w in clean.split() if w]
    if not words:
        return []

    cands = []
    cands.append("".join(words))             # riotgames
    cands.append("-".join(words))            # riot-games
    # drop trailing suffix words (ai/labs/...)
    core = list(words)
    while len(core) > 1 and core[-1] in SUFFIXES:
        core.pop()
    if core != words:
        cands.append("".join(core))
        cands.append("-".join(core))
    cands.append(words[0])                    # first word only

    seen, out = set(), []
    for c in cands:
        if c and c not in seen:
            seen.add(c)
            out.append(c)
    return out


def resolve(name):
    """Return (name, {ats, slug, count}) or (name, None)."""
    for slug in candidate_slugs(name):
        for ats_name, adapter in ADAPTERS.items():
            jobs = adapter(slug)
            if jobs:
                return name, {"ats": ats_name, "slug": slug, "count": len(jobs)}
    return name, None


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--limit", type=int, default=0, help="only probe first N companies")
    ap.add_argument("--workers", type=int, default=12)
    args = ap.parse_args()

    companies = read_companies(COMPANIES_TXT)
    if args.limit:
        companies = companies[: args.limit]

    resolved, unresolved = {}, []
    print(f"Probing {len(companies)} companies...", file=sys.stderr)
    with ThreadPoolExecutor(max_workers=args.workers) as ex:
        futures = [ex.submit(resolve, c) for c in companies]
        for i, fut in enumerate(as_completed(futures), 1):
            name, res = fut.result()
            if res:
                resolved[name] = {"ats": res["ats"], "slug": res["slug"]}
                print(f"[{i}/{len(companies)}] OK  {name} -> {res['ats']}:{res['slug']} ({res['count']} jobs)", file=sys.stderr)
            else:
                unresolved.append(name)
                print(f"[{i}/{len(companies)}] --  {name}", file=sys.stderr)

    resolved = dict(sorted(resolved.items(), key=lambda kv: kv[0].lower()))
    unresolved.sort(key=str.lower)

    doc = {
        "companies": resolved,
        "unresolved": unresolved,
    }
    header = (
        "# Generated by discover.py. Hand-editable.\n"
        "# To add/fix a company, put it under `companies:` as:\n"
        "#   Company Name:\n"
        "#     ats: greenhouse|ashby|lever|workable|smartrecruiters\n"
        "#     slug: their-board-slug\n"
        f"# Resolved: {len(resolved)} / {len(companies)}  |  Unresolved: {len(unresolved)}\n\n"
    )
    with open(COMPANIES_YAML, "w") as f:
        f.write(header)
        yaml.safe_dump(doc, f, sort_keys=False, allow_unicode=True, default_flow_style=False)

    print(f"\nResolved {len(resolved)}/{len(companies)} -> {COMPANIES_YAML}", file=sys.stderr)


if __name__ == "__main__":
    main()
